platform:ios, '8.0' 
target "LinkAll" do
    #pod 'CocoaLumberjack', '~> 3.0.0'
    use_frameworks!
    pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
end
